# Header

menu:
  主页: /
  个人简历: /about

# SubNav
subnav:
  github: "https://github.com/yugasun"
  #weibo: "#"
  rss: "/atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "YugaSun"
  #jianshu: "#"
  #douban: "#"
  mail: "mailto:yuga.sun.bj@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  linkedin: "http://www.linkedin.com/in/%E8%BF%9C%E9%AB%98-%E5%AD%99-424a62107/"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

# Content

# 文章太长，截断按钮文字
excerpt_link: false
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '坚持原创技术分享，您的支持将鼓励我继续创作！'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.jpg
# 微信二维码图片地址
weixin: /img/wechat.jpg

# Miscellaneous
baidu_analytics: '28d4aea1680535e760d13d954b54eddc'
google_analytics: 'UA-85991013-1'
favicon: /favicon.ico

#你的头像url
avatar: /img/avatar.jpg

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

# 填写你自己的 shortname
disqus_shortname: yugasun

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友情链接'
  aboutme: '关于我'

friends:
  前端小武: https://xuexb.com
  JerryQu 的小站: https://imququ.com

aboutme: Yuga<br>08年毕业于湖北大学<br>荣获国家一等奖学金<br><br>热爱前端技术<br>喜欢研究各种前沿技术<br>热爱运动，喜欢交朋友。<br>
