language: node_js
node_js:
  - "7"
compiler: gcc
os:
  - linux

env:
  global:
    - GH_REF: github.com/yugasun/yugasun.github.io.git
    - secure: "iPvEyC88zMU8nNfKH5FxQv7+XN5XfPFnMjiEgyKdxawjkMJkslcVCfDGriKGenmldMCiDE4shzZ8QKV0ImxqG+LjBmHhMsGntDX0GqRxz+o3QbbmPEzUt4ATHnF2QDDIMMtZ9tg6pg6JCtcEki7d56d16Kscv4QYdfQgJbJC8ZcizvVzFTuCpIddPQZOfDIIxNm3m1cLpAIDcdE0fB1B3NyGuB0nCSv2PSyNRCrPKlhi/JE3esAFq6Nl0h0LKJVqB6GgC2zMRSpxgNBl0NxHY57iNR1Aux8WEWuY6qWNdilBcYJTujyDshGxJGu4BsRZy4kJaBuqAa8hVZ1lPurPU+R5Xlsj0vSjGTY5k+UwW8uyxMVTs8kaRLlkCsGsaIFQCKvU95CFU4H8WCBTf4jZmDbAnSdr0mxH/JGHzoDRLSIZFlbWyOtrjVcVLNuwdBD0AcHH/HZouEIyqwtDCpjjE/Psw8lhlGLrJci7U7/LTlewOf0EzymDKsuPy93duREkq1HhCuUhcN84phPM8E1j/lctygVMS0XxSLr9gnWGmzJx+8Zodcr+rzNMLIaLMkCfZmGzszCwJAJkPU2yakHGzAXcM9BCv+rCyBQvPuDFx6q7zePWXnWPJonbxI11CQbNYDVCS3HfhVu24pauGuGzr8/PQmJyqgKYHjSUJ3e5Jj0="

# S: Build Lifecycle
install:
  - yarn install
script:
  - yarn run gen
after_script:
  - cd public
  - git init
  - git config user.name 'yugasun'
  - git config user.email 'yuga_sun@163.com'
  - git add .
  - git commit -m "Update sites"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle