name: Build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repsitory
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          registry-url: https://registry.npmjs.org

      - name: Retrive dependencies from cache
        id: cacheNpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-v10-${{ runner.os }}-${{ github.ref }}-${{ hashFile('package.json') }}
          restore-keys: npm-v10-${{ runner.os }}-${{ github.ref}}
            npm-v10-${{ runner.os }}-refs/heads/master-

      - name: Install dependencies
        if: steps.cacheNpm.outputs.cache-hit != 'true'
        run: |
          npm update --no-save
          npm update --save-dev --no-save

      - name: Build
        run: npm run gen

      - name: Test
        run: npm run test
